// <auto-generated />
using KISSG.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KISSG.Migrations
{
    [DbContext(typeof(welcomeContext))]
    [Migration("20190130194116_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KISSG.Templates.OnePageSite.welcome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("ContactSectionBgColor");

                    b.Property<string>("ContactSectionTxtColor");

                    b.Property<string>("Email");

                    b.Property<string>("FirstSectionColor");

                    b.Property<string>("LogoUrl");

                    b.Property<string>("MainSection");

                    b.Property<string>("MainSectionBgColor");

                    b.Property<string>("MainSectionTxtColor");

                    b.Property<string>("Motto");

                    b.Property<string>("MottoColor");

                    b.Property<string>("Phone");

                    b.Property<string>("PictureUrl");

                    b.Property<string>("Projects");

                    b.HasKey("Id");

                    b.ToTable("Welcomes");
                });
#pragma warning restore 612, 618
        }
    }
}
